-- 코드를 입력하세요

# SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, (SUM(BOOK_SALES.SALES) * book.price) TOTAL_PRICE FROM BOOK 
# JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
# JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
# WHERE BOOK_SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31' GROUP BY AUTHOR_ID, CATEGORY ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

select p.AUTHOR_ID, p.AUTHOR_NAME, p.CATEGORY, sum(p.price) TOTAL_SALES from (
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, 
        CATEGORY, BOOK_SALES.book_id, 
        (sum(sales) * price) price 
    FROM BOOK 
    JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
    WHERE BOOK_SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    group by BOOK_SALES.book_id, AUTHOR_ID, CATEGORY
) p group by p.AUTHOR_ID, p.CATEGORY order by p.AUTHOR_ID asc, p.CATEGORY desc;