-- 코드를 입력하세요

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.TOTAL) AS TOTAL_SALES FROM (
SELECT FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME, (AMOUNT * PRICE) AS TOTAL from FOOD_ORDER 
    join FOOD_PRODUCT on FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31') 
A GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
;



