-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM (PRICE) TOTAL_SALES from USED_GOODS_USER 
    join USED_GOODS_BOARD on 
    USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
    WHERE USED_GOODS_BOARD.STATUS = 'DONE'
    GROUP BY USER_ID, NICKNAME
    HAVING TOTAL_SALES >= 700000
    ORDER BY TOTAL_SALES;
    
    
# SELECT * FROM USED_GOODS_USER WHERE STATUS = 'DONE' AND PRICE >= 700000;