-- 코드를 입력하세요
# SELECT * FROM REST_REVIEW
    # JOIN MEMBER_PROFILE ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID;

SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, date_format(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE  FROM REST_REVIEW 
JOIN  MEMBER_PROFILE ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
WHERE REST_REVIEW.MEMBER_ID IN (
    SELECT A.MEMBER_ID FROM (
    SELECT COUNT(*) AS NUM, MEMBER_ID FROM (
    REST_REVIEW
    ) GROUP BY MEMBER_ID having NUM = (SELECT COUNT(*) AS CNT FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY CNT DESC LIMIT 1)
    ) A
) ORDER BY REST_REVIEW.REVIEW_DATE, REST_REVIEW.REVIEW_TEXT;



